/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-autumn-forest-3ba29976640c4b26a66d6cea0556b7d6
Title: FREE - SkyBox Autumn Forest
*/

import React, { useRef, useEffect, useLayoutEffect } from 'react'
import { useFrame, useThree } from '@react-three/fiber'
import { useGLTF, useScroll, OrbitControls } from '@react-three/drei'

export default function Scene(props) {
  const { nodes, materials, scene } = useGLTF('/scene.gltf')

  return (
    <group {...props} dispose={null}>
      <group scale={[0.01, 0.01, 0.01]}>
        <mesh geometry={nodes.Sphere__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={50000} />
      </group>
      {/*  <OrbitControls*/}
      {/*  enablePan={false}*/}
      {/*  enableZoom={false}*/}
      {/*  enableDamping*/}
      {/*  dampingFactor={0.5}*/}
      {/*  rotateSpeed={0.13}*/}
      {/*  mouseButtons={{ LEFT: 1, RIGHT: null, MIDDLE: null }}*/}
      {/*/>*/}
    </group>
  );
}

useGLTF.preload('/scene.gltf')
